---
title: "B Cells FACS"
output: html_notebook
---
```{r}
library(Seurat)
library(tidyverse)
library(here)
source(here('vignettes', 'bcells', 'common.R'))

load(here('vignettes', 'bcells', 'facs_cd19.Robj'))
```


```{r}
table(tiss_facs_cd19@ident)
```


```{r}
cluster.markers = FindAllMarkers(object = tiss_facs_cd19, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25)
head(cluster.markers)
```

```{r}
cluster.markers %>% group_by(cluster) %>% top_n(-10, p_val_adj)
```

```{r}
write_markers(cluster.markers, here('vignettes', 'bcells', 'facs_cluster_markers.csv'))
```



```{r}
top_cluster_markers = cluster.markers %>% group_by(ident) %>% top_n(-10, p_val_adj)
```


```{r, fig.height=40}
nCol = 4
plots = FeaturePlot(tiss_facs_cd19, features.plot = sort(unique(top_cluster_markers$gene)), 
                    do.return = TRUE, nCol = nCol, no.axes=TRUE, 
                    # Light grey to 
                    cols.use=c('lightgrey', '#008080'))
for (p in plots){
  gene_name = p$labels$title
  gene_tissues = top_organ_markers %>% filter(gene == p$labels$title) %>% select(tissue)
  gene_tissues = as.character(as.vector(gene_tissues$tissue))
  print(paste(gene_name, paste(gene_tissues)))
  title = paste0(gene_name, ' (', paste(gene_tissues, sep=', '), ')')
  p = p + labs(title=title)
  plots[[gene_name]] = p
}
plots.combined <- plot_grid(plotlist = plots, ncol = nCol)
invisible(x = lapply(X = plots.combined, FUN = print))
ggsave('facs_featureplot_top_cluster_markers.pdf', height = 40, width=15)
```


```{r}
organ_markers = find_markers(tiss_facs_cd19, 'tissue')
head(organ_markers)
```

```{r}
tissue_cell_counts = table(tiss_facs_cd19@meta.data$tissue)
print(tissue_cell_counts)

tissues_with_enough_cells = tissue_cell_counts[tissue_cell_counts > 50]
tissues_with_enough_cells
```


```{r}
organ_markers_enough_cells = filter(organ_markers, tissue %in% names(tissues_with_enough_cells))
organ_markers_enough_cells
```



```{r}
write_markers(organ_markers_enough_cells, '~/tabula-muris-vignettes/vignettes/bcells/tissue_markers.csv')
```


```{r}
ggplot(data=organ_markers_enough_cells, aes(x=p_val)) + geom_histogram() + facet_grid(~tissue)
```
```{r}
ggplot(data=organ_markers_enough_cells, aes(x=p_val_adj)) + geom_histogram() + facet_grid(~tissue)
```
```{r}
library(tidyverse)
```



```{r}
top_organ_markers = organ_markers_enough_cells %>% group_by(tissue) %>% top_n(-10, p_val_adj)
top_organ_markers
```


```{r, fig.height=40}
nCol = 4
plots = FeaturePlot(tiss_facs_cd19, features.plot = sort(unique(top_organ_markers$gene)), 
                    do.return = TRUE, nCol = nCol, no.axes=TRUE, 
                    # Light grey to 
                    cols.use=c('lightgrey', '#008080'))
for (p in plots){
  gene_name = p$labels$title
  gene_tissues = top_organ_markers %>% filter(gene == p$labels$title) %>% select(tissue)
  gene_tissues = as.character(as.vector(gene_tissues$tissue))
  print(paste(gene_name, paste(gene_tissues)))
  title = paste0(gene_name, ' (', paste(gene_tissues, sep=', '), ')')
  p = p + labs(title=title)
  plots[[gene_name]] = p
}
plots.combined <- plot_grid(plotlist = plots, ncol = nCol)
invisible(x = lapply(X = plots.combined, FUN = print))
ggsave('facs_featureplot_top_organ_markers.pdf', height = 40, width=15)
```

