---
title: "B Cells FACS"
output: html_notebook
---
```{r}
library(Seurat)
library(tidyverse)
library(here)
source(here('vignettes', 'bcells', 'common.R'))

load(here('vignettes', 'bcells', 'facs_cd19.Robj'))

tiss_facs_cd19@meta.data[,'pca.cluster.ids'] = as.numeric(tiss_facs_cd19@ident)
```


## Do ICA

```{r, fig.height=4, fig.width=8, echo=FALSE}
tiss_facs_cd19 <- RunICA(object = tiss_facs_cd19)
tiss_facs_cd19 <- ProjectDim(object = tiss_facs_cd19, reduction.type = 'ica')
```
```{r}
ICHeatmap(object = tiss_facs_cd19, ic.use = 1:6, cells.use = 500, do.balanced = TRUE, label.columns = FALSE, num.genes = 8)
```



Find clusters using ICA

```{r}
DimElbowPlot(tiss_facs_cd19, reduction.type="ica")
```



```{r}
ics.use = 5
```


```{r}
ICAPlot(tiss_facs_cd19)
ICAPlot(tiss_facs_cd19, group.by='tissue')
```

```{r}
PCAPlot(tiss_facs_cd19)
```


```{r}
ICAPlot(tiss_facs_cd19, dim.1=2, dim.2=3)
```

```{r}
# Set resolution
sub.res.used <- .1

tiss_facs_cd19 <- FindClusters(object = tiss_facs_cd19, reduction.type = "ica",
    resolution = sub.res.used, print.output = 0, save.SNN = TRUE, dims.use = 1:ics.use)
```

```{r}
tiss_facs_cd19 <- RunTSNE(object = tiss_facs_cd19, seed.use = 10, perplexity=30, 
                          reduction.use="ica", dims.use = 1:ics.use)
TSNEPlot(tiss_facs_cd19)
```

```{r}
tiss_facs_cd19 = BuildClusterTree(tiss_facs_cd19)
PlotClusterTree(tiss_facs_cd19)
```


```{r}
table(tiss_droplet_cd19@ident, tiss_droplet_cd19@meta.data$pca)
```

```{r}
cluster3.markers = FindMarkers(tiss_facs_cd19, ident.1 = 3)
```


```{r}
write_markers(cluster3.markers, here('vignettes', 'bcells', 'facs_ica_cluster3_markers.csv'))
```



